#!url=https://raw.githubusercontent.com/trantienvn/trantienvn.github.io/main/shadowrocket/picsartGold.module
#!name=PicsArt
#!desc=Kích hoạt picsart gold free
[Script]
AdGuard = type=http-response, pattern=^https?:\/\/api\.picsart\.com\/.*shop\/subscription.*, requires-body=1, script-path=https://raw.githubusercontent.com/trantienvn/trantienvn.github.io/refs/heads/main/shadowrocket/picsartGold.js, timeout=60
[MITM]
hostname = %APPEND%.picsart.com
