#!url=https://raw.githubusercontent.com/trantienvn/trantienvn.github.io/main/shadowrocket/picsartGold.module
#!name=PicsArt
#!desc=Kích hoạt picsart gold free
[Script]
youtube.response = type=http-response,pattern=^https?:\/\/api\.picsart\.com\/.*shop\/subscription,requires-body=1,max-size=-1,binary-body-mode=1,engine=auto,script-path=https://raw.githubusercontent.com/trantienvn/trantienvn.github.io/refs/heads/main/shadowrocket/picsartGold.js
[MITM]
hostname = api.picsart.com
